faker category changes
leowald/yeshtikvah pull request #76
Opened 2024-12-10 07:05 UTC by SKupferstein

Made changes as requested.
Since there are only 8 categories, most end up not having children, or having just one child. If needed, I can change to create more categories.

2024-12-10 09:32 UTC, leowald requested changes
When I run this I don't get the category object for the sub categories.
I need it to be in a fomat like this:
{"categories":[{"id":"a7e58678ae977ec1d0aa9d03","count":668,"description":"Verecundia alii video voluptas avarus vos bonus viduo defungo.","slug":"hope","parent_id":0,"children":**[{"id":"2deded0ded60aed38ec1fcb0","count":633,"description":"Amplexus vos turpis reprehenderit cattus autem conturbo speculum suscipio.","slug":"hope","parent_id":0,"name":"chow natural soliloquy","image":"https://avatars.githubusercontent.com/u/93066714","iconColor":["#b3f63b","#caab5f"],"color":"#99eebc"}],**"name":"hope","image":"https://avatars.githubusercontent.com/u/60228085","iconColor":["#537d05","#aabb13"],"color":"#d87fdc"}]


But unlike the example above there could be more than one children.

2024-12-10 09:45 UTC, SKupferstein commented
Sorry, I didn't realize it needs to be a full object. I'll change it.

On Tue, 10 Dec 2024 at 11:32, leowald ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> When I run this I don't get the category object for the sub categories.
> I need it to be in a fomat like this:
> {"categories":[{"id":"a7e58678ae977ec1d0aa9d03","count":668,"description":"Verecundia
> alii video voluptas avarus vos bonus viduo
> defungo.","slug":"hope","parent_id":0,"children":*[{"id":"2deded0ded60aed38ec1fcb0","count":633,"description":"Amplexus
> vos turpis reprehenderit cattus autem conturbo speculum
> suscipio.","slug":"hope","parent_id":0,"name":"chow natural
> soliloquy","image":"https://avatars.githubusercontent.com/u/93066714
> <https://avatars.githubusercontent.com/u/93066714>","iconColor":["#b3f63b","#caab5f"],"color":"#99eebc"}],*
> "name":"hope","image":"https://avatars.githubusercontent.com/u/60228085
> ","iconColor":["#537d05","#aabb13"],"color":"#d87fdc"}]
>
> But unlike the example above there could be more than one children.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/76#pullrequestreview-2491655342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM7EJCOE24IRS2D7N7L2E2YMLAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJRGY2TKMZUGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-10 10:02 UTC, leowald commented
good question. Only the main categories should be included. The sub should
be under children.
You can take out the parent_id.
I just changed my mind on the way I want it to work.
Thanks.

On Tue, Dec 10, 2024 at 11:55 AM SKupferstein ***@***.***>
wrote:

> These sub-categories that show as children under the parent categories,
> should also be included in the main category array?
> for example, if I have category a, b , c, d, e with c and d children of a,
> should the category array be something like this: [{a
> children:c,d},{b},{e}] or [{a children:c,d},{b},{c},{d}{e}]
>
> On Tue, 10 Dec 2024 at 11:44, S.Kupferstein ***@***.***> wrote:
>
> > Sorry, I didn't realize it needs to be a full object. I'll change it.
> >
> > On Tue, 10 Dec 2024 at 11:32, leowald ***@***.***> wrote:
> >
> >> ***@***.**** requested changes on this pull request.
> >>
> >> When I run this I don't get the category object for the sub categories.
> >> I need it to be in a fomat like this:
> >>
> {"categories":[{"id":"a7e58678ae977ec1d0aa9d03","count":668,"description":"Verecundia
>
> >> alii video voluptas avarus vos bonus viduo
> >>
> defungo.","slug":"hope","parent_id":0,"children":*[{"id":"2deded0ded60aed38ec1fcb0","count":633,"description":"Amplexus
>
> >> vos turpis reprehenderit cattus autem conturbo speculum
> >> suscipio.","slug":"hope","parent_id":0,"name":"chow natural
> >> soliloquy","image":"https://avatars.githubusercontent.com/u/93066714
> >> <https://avatars.githubusercontent.com/u/93066714>","iconColor":["#b3f63b","#caab5f"],"color":"#99eebc"}],*
>
> >> "name":"hope","image":"https://avatars.githubusercontent.com/u/60228085
> >> ","iconColor":["#537d05","#aabb13"],"color":"#d87fdc"}]
> >>
> >> But unlike the example above there could be more than one children.
> >>
> >> —
> >> Reply to this email directly, view it on GitHub
> >> <
> https://github.com/leowald/yeshtikvah/pull/76#pullrequestreview-2491655342>,
>
> >> or unsubscribe
> >> <
> https://github.com/notifications/unsubscribe-auth/BFNBRM7EJCOE24IRS2D7N7L2E2YMLAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJRGY2TKMZUGI>
>
> >> .
> >> You are receiving this because you authored the thread.Message ID:
> >> ***@***.***>
> >>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/76#issuecomment-2531056483>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5BZJKBD5RUL7S6JLSDOUD32E23CBAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGA2TMNBYGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-10 11:36 UTC, SKupferstein commented
OK
So there should be an array of 8 categories that some of them have
subcategories under them, or there should be 8 categories in total?

On Tue, 10 Dec 2024 at 12:02, leowald ***@***.***> wrote:

> good question. Only the main categories should be included. The sub should
> be under children.
> You can take out the parent_id.
> I just changed my mind on the way I want it to work.
> Thanks.
>
> On Tue, Dec 10, 2024 at 11:55 AM SKupferstein ***@***.***>
> wrote:
>
> > These sub-categories that show as children under the parent categories,
> > should also be included in the main category array?
> > for example, if I have category a, b , c, d, e with c and d children of
> a,
> > should the category array be something like this: [{a
> > children:c,d},{b},{e}] or [{a children:c,d},{b},{c},{d}{e}]
> >
> > On Tue, 10 Dec 2024 at 11:44, S.Kupferstein ***@***.***> wrote:
> >
> > > Sorry, I didn't realize it needs to be a full object. I'll change it.
> > >
> > > On Tue, 10 Dec 2024 at 11:32, leowald ***@***.***> wrote:
> > >
> > >> ***@***.**** requested changes on this pull request.
> > >>
> > >> When I run this I don't get the category object for the sub
> categories.
> > >> I need it to be in a fomat like this:
> > >>
> >
> {"categories":[{"id":"a7e58678ae977ec1d0aa9d03","count":668,"description":"Verecundia
>
> >
> > >> alii video voluptas avarus vos bonus viduo
> > >>
> >
> defungo.","slug":"hope","parent_id":0,"children":*[{"id":"2deded0ded60aed38ec1fcb0","count":633,"description":"Amplexus
>
> >
> > >> vos turpis reprehenderit cattus autem conturbo speculum
> > >> suscipio.","slug":"hope","parent_id":0,"name":"chow natural
> > >> soliloquy","image":"https://avatars.githubusercontent.com/u/93066714
> > >> <https://avatars.githubusercontent.com/u/93066714>","iconColor":["#b3f63b","#caab5f"],"color":"#99eebc"}],*
>
> >
> > >> "name":"hope","image":"
> https://avatars.githubusercontent.com/u/60228085
> > >> ","iconColor":["#537d05","#aabb13"],"color":"#d87fdc"}]
> > >>
> > >> But unlike the example above there could be more than one children.
> > >>
> > >> —
> > >> Reply to this email directly, view it on GitHub
> > >> <
> >
> https://github.com/leowald/yeshtikvah/pull/76#pullrequestreview-2491655342>,
>
> >
> > >> or unsubscribe
> > >> <
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM7EJCOE24IRS2D7N7L2E2YMLAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJRGY2TKMZUGI>
>
> >
> > >> .
> > >> You are receiving this because you authored the thread.Message ID:
> > >> ***@***.***>
> > >>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/leowald/yeshtikvah/pull/76#issuecomment-2531056483>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A5BZJKBD5RUL7S6JLSDOUD32E23CBAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGA2TMNBYGM>
>
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/76#issuecomment-2531074476>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM4WWIUGZEGUQSO4BUD2E233JAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGA3TINBXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-10 12:25 UTC, leowald commented
It doesn't really matter. whatever way you want to do it.

On Tue, Dec 10, 2024 at 1:36 PM SKupferstein ***@***.***>
wrote:

> OK
> So there should be an array of 8 categories that some of them have
> subcategories under them, or there should be 8 categories in total?
>
> On Tue, 10 Dec 2024 at 12:02, leowald ***@***.***> wrote:
>
> > good question. Only the main categories should be included. The sub
> should
> > be under children.
> > You can take out the parent_id.
> > I just changed my mind on the way I want it to work.
> > Thanks.
> >
> > On Tue, Dec 10, 2024 at 11:55 AM SKupferstein ***@***.***>
> > wrote:
> >
> > > These sub-categories that show as children under the parent
> categories,
> > > should also be included in the main category array?
> > > for example, if I have category a, b , c, d, e with c and d children
> of
> > a,
> > > should the category array be something like this: [{a
> > > children:c,d},{b},{e}] or [{a children:c,d},{b},{c},{d}{e}]
> > >
> > > On Tue, 10 Dec 2024 at 11:44, S.Kupferstein ***@***.***> wrote:
> > >
> > > > Sorry, I didn't realize it needs to be a full object. I'll change
> it.
> > > >
> > > > On Tue, 10 Dec 2024 at 11:32, leowald ***@***.***> wrote:
> > > >
> > > >> ***@***.**** requested changes on this pull request.
> > > >>
> > > >> When I run this I don't get the category object for the sub
> > categories.
> > > >> I need it to be in a fomat like this:
> > > >>
> > >
> >
> {"categories":[{"id":"a7e58678ae977ec1d0aa9d03","count":668,"description":"Verecundia
>
> >
> > >
> > > >> alii video voluptas avarus vos bonus viduo
> > > >>
> > >
> >
> defungo.","slug":"hope","parent_id":0,"children":*[{"id":"2deded0ded60aed38ec1fcb0","count":633,"description":"Amplexus
>
> >
> > >
> > > >> vos turpis reprehenderit cattus autem conturbo speculum
> > > >> suscipio.","slug":"hope","parent_id":0,"name":"chow natural
> > > >> soliloquy","image":"
> https://avatars.githubusercontent.com/u/93066714
> > > >> <https://avatars.githubusercontent.com/u/93066714>","iconColor":["#b3f63b","#caab5f"],"color":"#99eebc"}],*
>
> >
> > >
> > > >> "name":"hope","image":"
> > https://avatars.githubusercontent.com/u/60228085
> > > >> ","iconColor":["#537d05","#aabb13"],"color":"#d87fdc"}]
> > > >>
> > > >> But unlike the example above there could be more than one children.
> > > >>
> > > >> —
> > > >> Reply to this email directly, view it on GitHub
> > > >> <
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/76#pullrequestreview-2491655342>,
>
> >
> > >
> > > >> or unsubscribe
> > > >> <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM7EJCOE24IRS2D7N7L2E2YMLAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJRGY2TKMZUGI>
>
> >
> > >
> > > >> .
> > > >> You are receiving this because you authored the thread.Message ID:
> > > >> ***@***.***>
> > > >>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/leowald/yeshtikvah/pull/76#issuecomment-2531056483>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKBD5RUL7S6JLSDOUD32E23CBAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGA2TMNBYGM>
>
> >
> > > .
> > > You are receiving this because you commented.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/leowald/yeshtikvah/pull/76#issuecomment-2531074476>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BFNBRM4WWIUGZEGUQSO4BUD2E233JAVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGA3TINBXGY>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/76#issuecomment-2531320053>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5BZJKGXBUMIJAMH5UJLCX32E3G33AVCNFSM6AAAAABTKO235CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZRGMZDAMBVGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-01-20 07:14 UTC, leowald requested changes
I ran this code but don't see children coming up for any of the categories.

2025-01-20 08:05 UTC, leowald approved these changes
Looks great

2025-01-20 08:06 UTC, merged