24 buttons
leowald/yeshtikvah pull request #82
Opened 2024-12-15 11:41 UTC by SKupferstein

2024-12-16 19:04 UTC, SKupferstein commented
Oops, there was a bug there.
All fixed now, pushed again.

On Mon, 16 Dec 2024 at 12:02, leowald ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> When I run storybook to check it I get an error: Error: type is not defined
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2505708580>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM6VKPOOO2QBOSV4SRD2F2QLHAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBVG4YDQNJYGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-17 10:19 UTC, leowald requested changes
Overall looks good.

- [ ] I think there is css missing though. We want the button except for the size and color to look like it did in the original template and it is missing some elements.
- [ ] In storybook, I noticed a typo: The bacground color of the button - can be a string OR
- [ ] In storybook what is the empty theme - the last one?
- [ ] In storybook, icon does not work
- [ ] In general the default size should be set to medium. I don't think it is.
- [ ] We have to deal with when the background color is a graident and outline is true, that does not work - but I will open up another issue to deal with and assign to you as it is a whole issue in itself.
Please make those changes and then I'll check over again to make sure all is working and I'll check the tests also.

2024-12-17 12:08 UTC, SKupferstein commented
Working on it.
1. Sorry I missed this - 2 questions: - The padding looks too little to me,
especially with added icon. Can I add padding? - on the original template
the gradient is up to down and switches directions when hover. Do you
expect me to do it here as well? if yes - should gradient always be
up-to-down or whatever passed in should be switched to opposite direction?
2. Not sure what is not correct?
3. empty theme - basically if someone tries to apply themes in storybook
they should have an option of going back to see how the button looks
without a theme (it's radio buttons so they can't be un-clicked, once you
choose one, you have to stay with one of them)
4. It works for me, but in the beginning I was getting errors. Can you tell
me what you're seeing?
5. Seems to be working by me, can you check again?
6. You are right, please assign to me and I'll work on it after I'm done
with this.

Thank you so much!

On Tue, 17 Dec 2024 at 12:19, leowald ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Overall looks good.
>
>    - I think there is css missing though. We want the button except for
>    the size and color to look like it did in the original template and it is
>    missing some elements.
>    - In storybook, I noticed a typo: The bacground color of the button -
>    can be a string OR
>    - In storybook what is the empty theme - the last one?
>    - In storybook, icon does not work
>    - In general the default size should be set to medium. I don't think
>    it is.
>    - We have to deal with when the background color is a graident and
>    outline is true, that does not work - but I will open up another issue to
>    deal with and assign to you as it is a whole issue in itself.
>    Please make those changes and then I'll check over again to make sure
>    all is working and I'll check the tests also.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2508452281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM7RVL7LM4VB7IV6HED2F73E7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBYGQ2TEMRYGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-18 06:38 UTC, leowald commented
1.The padding is put on the sm, md, lg and on the text div, like in the template. I think for the text div I have it set as 7px - see if that makes it look better. If not, you can play around with it.

No, to does not have to switch onhover - we do that in a different issue.

2. The spelling of the word.

3.Ok so make it clear that it is for an empty theme somehow, because I didn't understand it.

4. When I click on the set icon, I get: Cannot read properties of undefined (reading 'style')
5. Ok for the medium


> Working on it. 1. Sorry I missed this - 2 questions: - The padding looks too little to me, especially with added icon. Can I add padding? - on the original template the gradient is up to down and switches directions when hover. Do you expect me to do it here as well? if yes - should gradient always be up-to-down or whatever passed in should be switched to opposite direction? 2. Not sure what is not correct? 3. empty theme - basically if someone tries to apply themes in storybook they should have an option of going back to see how the button looks without a theme (it's radio buttons so they can't be un-clicked, once you choose one, you have to stay with one of them) 4. It works for me, but in the beginning I was getting errors. Can you tell me what you're seeing? 5. Seems to be working by me, can you check again? 6. You are right, please assign to me and I'll work on it after I'm done with this. Thank you so much!
> […](#)
> On Tue, 17 Dec 2024 at 12:19, leowald ***@***.***> wrote: ***@***.**** requested changes on this pull request. Overall looks good. - I think there is css missing though. We want the button except for the size and color to look like it did in the original template and it is missing some elements. - In storybook, I noticed a typo: The bacground color of the button - can be a string OR - In storybook what is the empty theme - the last one? - In storybook, icon does not work - In general the default size should be set to medium. I don't think it is. - We have to deal with when the background color is a graident and outline is true, that does not work - but I will open up another issue to deal with and assign to you as it is a whole issue in itself. Please make those changes and then I'll check over again to make sure all is working and I'll check the tests also. — Reply to this email directly, view it on GitHub <[#82 (review)](https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2508452281)>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/BFNBRM7RVL7LM4VB7IV6HED2F73E7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBYGQ2TEMRYGE> . You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-12-22 08:30 UTC, leowald requested changes
The css looks better but still not all there.
Just taking a quick glance I can see that the link is underlined. It is not underlined in the original template. I also see at least one other thing. Take a look carefully and see if you can generate one of the buttons on the template exactly how it should be by using your component.

2024-12-22 08:36 UTC, SKupferstein commented
The template you're referring to this: [image: image.png]?

On Sun, 22 Dec 2024 at 10:30, leowald ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The css looks better but still not all there.
> Just taking a quick glance I can see that the link is underlined. It is
> not underlined in the original template. I also see at least one other
> thing. Take a look carefully and see if you can generate one of the buttons
> on the template exactly how it should be by using your component.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2519573871>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM5HM5GXM2OE7W2MUOT2GZ2B7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJZGU3TGOBXGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-22 08:39 UTC, leowald commented
https://www.shalach-manos.com/tikvah/

On Sun, Dec 22, 2024 at 10:36 AM SKupferstein ***@***.***>
wrote:

> The template you're referring to this: [image: image.png]?
>
> On Sun, 22 Dec 2024 at 10:30, leowald ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > The css looks better but still not all there.
> > Just taking a quick glance I can see that the link is underlined. It is
> > not underlined in the original template. I also see at least one other
> > thing. Take a look carefully and see if you can generate one of the
> buttons
> > on the template exactly how it should be by using your component.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2519573871>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BFNBRM5HM5GXM2OE7W2MUOT2GZ2B7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJZGU3TGOBXGE>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2558377979>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5BZJKAUJBXFVHRSDASLMU32GZ22HAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJYGM3TOOJXHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-24 09:18 UTC, leowald requested changes
It is getting better but what I want you to do is go to the template - look what file is creating that button. Go to the file and then the css should be almost the same. Where there are variables for example for font, there should still be variables ect. All properties should be the same except for color.

2024-12-25 11:21 UTC, leowald requested changes
You are making progress..
btw, this issue is meant to take a long time - it is complicated..

- [ ] I looked at the original scss vs yours and I'm wondering why you don't have dispaly: inline-block, border=0 ect.
- [ ] Why do you need the class rd - why can you add it to your default button class. Try it and figure out why you don't need it.
- [ ] Why in the props are you setting a default background color object?
- [ ] Why in button style do you have  position: "relative",
    zIndex: 0,
- [ ] This is really in a different task but there should not be a different solution for if the background color is linear variant or a color. There should be an outline class and you should apply it.

- [ ] This can all be simplified as the correct class can be read in directly from the prop passed in.
`    let className = `${style.button} `;
  className += extras.borderRadius ? "" : `${style.rd} `;
  className += extras.fontSize
    ? ""
    : (size === "sm" && style.sm) || (size === "lg" && style.lg) || style.md;
`

- [ ] In general you should get rid of any inline styles unless you need them like in the case of background, you have no choice. so position: "relative" - should not be there ect.
- [ ] I'm running storybook and see the text is not coming up uppercase?
- [ ] Simplify this line also  onClick={onClickFunction && (() => onClickFunction())}

2024-12-26 08:03 UTC, SKupferstein commented
Hi,
1. changed display to flex so that the icon should be in one line with
text, and border 0 - had that in the inline style - border:
      outline && typeof backgroundColor == "string"
        ? `1px solid ${getBackground(backgroundColor)}`
        : "none",
2. class rd - basically, if a bootstrap theme is applied, it overwrites the
border radius, therefore I had to add the !important tag to it, but if the
user adds his own border radius in "others", it won't override, so I put it
in an extra class to add it conditionally.
3. Did it when you asked me to make css look like template and I wasn't
sure what you meant... guess I can remove
4. These I added in the other tasks dealing with gradient border and text,
it's not necessary here but I guess they'll be merged in the end anyway...
5. If the background color is gradient then I couldn't add it to the
background, I had to add a div under the text with the gradient outline
6.Will do
7.In the template you used "capitalize" which only changes the first letter
to uppercase - let me know if I should change
8.Will do

Thank you

On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> You are making progress..
> btw, this issue is meant to take a long time - it is complicated..
>
>    -
>
>    I looked at the original scss vs yours and I'm wondering why you don't
>    have dispaly: inline-block, border=0 ect.
>    -
>
>    Why do you need the class rd - why can you add it to your default
>    button class. Try it and figure out why you don't need it.
>    -
>
>    Why in the props are you setting a default background color object?
>    -
>
>    Why in button style do you have position: "relative",
>    zIndex: 0,
>    -
>
>    This is really in a different task but there should not be a different
>    solution for if the background color is linear variant or a color. There
>    should be an outline class and you should apply it.
>    -
>
>    This can all be simplified as the correct class can be read in
>    directly from the prop passed in.
>    let className =${style.button} ; className += extras.borderRadius ? ""
>    : ${style.rd} ; className += extras.fontSize ? "" : (size === "sm" &&
>    style.sm) || (size === "lg" && style.lg) || style.md;
>    -
>
>    In general you should get rid of any inline styles unless you need
>    them like in the case of background, you have no choice. so position:
>    "relative" - should not be there ect.
>    -
>
>    I'm running storybook and see the text is not coming up uppercase?
>    -
>
>    Simplify this line also onClick={onClickFunction && (() =>
>    onClickFunction())}
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-26 09:39 UTC, leowald commented
I actually took out number 7, it is fine and you can ignore.
All other things can be done and should be to bring your code up a level.
Again this is not an easy task - but it is all doable the way I'm saying.
(the only other thing you can probably ignore if you have a good reason for
it is why you don't put the display: inline-block.

On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
wrote:

> Hi,
> 1. changed display to flex so that the icon should be in one line with
> text, and border 0 - had that in the inline style - border:
> outline && typeof backgroundColor == "string"
> ? `1px solid ${getBackground(backgroundColor)}`
> : "none",
> 2. class rd - basically, if a bootstrap theme is applied, it overwrites
> the
> border radius, therefore I had to add the !important tag to it, but if the
> user adds his own border radius in "others", it won't override, so I put
> it
> in an extra class to add it conditionally.
> 3. Did it when you asked me to make css look like template and I wasn't
> sure what you meant... guess I can remove
> 4. These I added in the other tasks dealing with gradient border and text,
> it's not necessary here but I guess they'll be merged in the end anyway...
> 5. If the background color is gradient then I couldn't add it to the
> background, I had to add a div under the text with the gradient outline
> 6.Will do
> 7.In the template you used "capitalize" which only changes the first
> letter
> to uppercase - let me know if I should change
> 8.Will do
>
> Thank you
>
> On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
>
> > ***@***.**** requested changes on this pull request.
> >
> > You are making progress..
> > btw, this issue is meant to take a long time - it is complicated..
> >
> > -
> >
> > I looked at the original scss vs yours and I'm wondering why you don't
> > have dispaly: inline-block, border=0 ect.
> > -
> >
> > Why do you need the class rd - why can you add it to your default
> > button class. Try it and figure out why you don't need it.
> > -
> >
> > Why in the props are you setting a default background color object?
> > -
> >
> > Why in button style do you have position: "relative",
> > zIndex: 0,
> > -
> >
> > This is really in a different task but there should not be a different
> > solution for if the background color is linear variant or a color. There
> > should be an outline class and you should apply it.
> > -
> >
> > This can all be simplified as the correct class can be read in
> > directly from the prop passed in.
> > let className =${style.button} ; className += extras.borderRadius ? ""
> > : ${style.rd} ; className += extras.fontSize ? "" : (size === "sm" &&
> > style.sm) || (size === "lg" && style.lg) || style.md;
> > -
> >
> > In general you should get rid of any inline styles unless you need
> > them like in the case of background, you have no choice. so position:
> > "relative" - should not be there ect.
> > -
> >
> > I'm running storybook and see the text is not coming up uppercase?
> > -
> >
> > Simplify this line also onClick={onClickFunction && (() =>
> > onClickFunction())}
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-26 09:58 UTC, SKupferstein commented
Is it ok if I work from issue 83 on both issues?

On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:

> I actually took out number 7, it is fine and you can ignore.
> All other things can be done and should be to bring your code up a level.
> Again this is not an easy task - but it is all doable the way I'm saying.
> (the only other thing you can probably ignore if you have a good reason
> for
> it is why you don't put the display: inline-block.
>
> On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> wrote:
>
> > Hi,
> > 1. changed display to flex so that the icon should be in one line with
> > text, and border 0 - had that in the inline style - border:
> > outline && typeof backgroundColor == "string"
> > ? `1px solid ${getBackground(backgroundColor)}`
> > : "none",
> > 2. class rd - basically, if a bootstrap theme is applied, it overwrites
> > the
> > border radius, therefore I had to add the !important tag to it, but if
> the
> > user adds his own border radius in "others", it won't override, so I put
> > it
> > in an extra class to add it conditionally.
> > 3. Did it when you asked me to make css look like template and I wasn't
> > sure what you meant... guess I can remove
> > 4. These I added in the other tasks dealing with gradient border and
> text,
> > it's not necessary here but I guess they'll be merged in the end
> anyway...
> > 5. If the background color is gradient then I couldn't add it to the
> > background, I had to add a div under the text with the gradient outline
> > 6.Will do
> > 7.In the template you used "capitalize" which only changes the first
> > letter
> > to uppercase - let me know if I should change
> > 8.Will do
> >
> > Thank you
> >
> > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> >
> > > ***@***.**** requested changes on this pull request.
> > >
> > > You are making progress..
> > > btw, this issue is meant to take a long time - it is complicated..
> > >
> > > -
> > >
> > > I looked at the original scss vs yours and I'm wondering why you don't
> > > have dispaly: inline-block, border=0 ect.
> > > -
> > >
> > > Why do you need the class rd - why can you add it to your default
> > > button class. Try it and figure out why you don't need it.
> > > -
> > >
> > > Why in the props are you setting a default background color object?
> > > -
> > >
> > > Why in button style do you have position: "relative",
> > > zIndex: 0,
> > > -
> > >
> > > This is really in a different task but there should not be a different
> > > solution for if the background color is linear variant or a color.
> There
> > > should be an outline class and you should apply it.
> > > -
> > >
> > > This can all be simplified as the correct class can be read in
> > > directly from the prop passed in.
> > > let className =${style.button} ; className += extras.borderRadius ? ""
> > > : ${style.rd} ; className += extras.fontSize ? "" : (size === "sm" &&
> > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > -
> > >
> > > In general you should get rid of any inline styles unless you need
> > > them like in the case of background, you have no choice. so position:
> > > "relative" - should not be there ect.
> > > -
> > >
> > > I'm running storybook and see the text is not coming up uppercase?
> > > -
> > >
> > > Simplify this line also onClick={onClickFunction && (() =>
> > > onClickFunction())}
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
>
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562371237>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRM3UTRK3AR4YBEX2EWL2HPFHNAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM3TCMRTG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-26 10:23 UTC, leowald commented
Yes

On Thu, Dec 26, 2024 at 11:58 AM SKupferstein ***@***.***>
wrote:

> Is it ok if I work from issue 83 on both issues?
>
> On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:
>
> > I actually took out number 7, it is fine and you can ignore.
> > All other things can be done and should be to bring your code up a
> level.
> > Again this is not an easy task - but it is all doable the way I'm
> saying.
> > (the only other thing you can probably ignore if you have a good reason
> > for
> > it is why you don't put the display: inline-block.
> >
> > On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> > wrote:
> >
> > > Hi,
> > > 1. changed display to flex so that the icon should be in one line with
> > > text, and border 0 - had that in the inline style - border:
> > > outline && typeof backgroundColor == "string"
> > > ? `1px solid ${getBackground(backgroundColor)}`
> > > : "none",
> > > 2. class rd - basically, if a bootstrap theme is applied, it
> overwrites
> > > the
> > > border radius, therefore I had to add the !important tag to it, but if
> > the
> > > user adds his own border radius in "others", it won't override, so I
> put
> > > it
> > > in an extra class to add it conditionally.
> > > 3. Did it when you asked me to make css look like template and I
> wasn't
> > > sure what you meant... guess I can remove
> > > 4. These I added in the other tasks dealing with gradient border and
> > text,
> > > it's not necessary here but I guess they'll be merged in the end
> > anyway...
> > > 5. If the background color is gradient then I couldn't add it to the
> > > background, I had to add a div under the text with the gradient
> outline
> > > 6.Will do
> > > 7.In the template you used "capitalize" which only changes the first
> > > letter
> > > to uppercase - let me know if I should change
> > > 8.Will do
> > >
> > > Thank you
> > >
> > > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> > >
> > > > ***@***.**** requested changes on this pull request.
> > > >
> > > > You are making progress..
> > > > btw, this issue is meant to take a long time - it is complicated..
> > > >
> > > > -
> > > >
> > > > I looked at the original scss vs yours and I'm wondering why you
> don't
> > > > have dispaly: inline-block, border=0 ect.
> > > > -
> > > >
> > > > Why do you need the class rd - why can you add it to your default
> > > > button class. Try it and figure out why you don't need it.
> > > > -
> > > >
> > > > Why in the props are you setting a default background color object?
> > > > -
> > > >
> > > > Why in button style do you have position: "relative",
> > > > zIndex: 0,
> > > > -
> > > >
> > > > This is really in a different task but there should not be a
> different
> > > > solution for if the background color is linear variant or a color.
> > There
> > > > should be an outline class and you should apply it.
> > > > -
> > > >
> > > > This can all be simplified as the correct class can be read in
> > > > directly from the prop passed in.
> > > > let className =${style.button} ; className += extras.borderRadius ?
> ""
> > > > : ${style.rd} ; className += extras.fontSize ? "" : (size === "sm"
> &&
> > > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > > -
> > > >
> > > > In general you should get rid of any inline styles unless you need
> > > > them like in the case of background, you have no choice. so
> position:
> > > > "relative" - should not be there ect.
> > > > -
> > > >
> > > > I'm running storybook and see the text is not coming up uppercase?
> > > > -
> > > >
> > > > Simplify this line also onClick={onClickFunction && (() =>
> > > > onClickFunction())}
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > >
> > > > .
> > > > You are receiving this because you authored the thread.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
>
> >
> > > .
> > > You are receiving this because you commented.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562371237>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BFNBRM3UTRK3AR4YBEX2EWL2HPFHNAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM3TCMRTG4>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562386492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5BZJKHGDTEOQIALJLTKKAD2HPHL7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM4DMNBZGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-26 10:26 UTC, SKupferstein commented
ok
and can we decide that in 'others' the user can't put in border radius...?
because this is making it very complicated:)

On Thu, 26 Dec 2024 at 12:24, leowald ***@***.***> wrote:

> Yes
>
> On Thu, Dec 26, 2024 at 11:58 AM SKupferstein ***@***.***>
> wrote:
>
> > Is it ok if I work from issue 83 on both issues?
> >
> > On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:
> >
> > > I actually took out number 7, it is fine and you can ignore.
> > > All other things can be done and should be to bring your code up a
> > level.
> > > Again this is not an easy task - but it is all doable the way I'm
> > saying.
> > > (the only other thing you can probably ignore if you have a good
> reason
> > > for
> > > it is why you don't put the display: inline-block.
> > >
> > > On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> > > wrote:
> > >
> > > > Hi,
> > > > 1. changed display to flex so that the icon should be in one line
> with
> > > > text, and border 0 - had that in the inline style - border:
> > > > outline && typeof backgroundColor == "string"
> > > > ? `1px solid ${getBackground(backgroundColor)}`
> > > > : "none",
> > > > 2. class rd - basically, if a bootstrap theme is applied, it
> > overwrites
> > > > the
> > > > border radius, therefore I had to add the !important tag to it, but
> if
> > > the
> > > > user adds his own border radius in "others", it won't override, so I
> > put
> > > > it
> > > > in an extra class to add it conditionally.
> > > > 3. Did it when you asked me to make css look like template and I
> > wasn't
> > > > sure what you meant... guess I can remove
> > > > 4. These I added in the other tasks dealing with gradient border and
> > > text,
> > > > it's not necessary here but I guess they'll be merged in the end
> > > anyway...
> > > > 5. If the background color is gradient then I couldn't add it to the
> > > > background, I had to add a div under the text with the gradient
> > outline
> > > > 6.Will do
> > > > 7.In the template you used "capitalize" which only changes the first
> > > > letter
> > > > to uppercase - let me know if I should change
> > > > 8.Will do
> > > >
> > > > Thank you
> > > >
> > > > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> > > >
> > > > > ***@***.**** requested changes on this pull request.
> > > > >
> > > > > You are making progress..
> > > > > btw, this issue is meant to take a long time - it is complicated..
> > > > >
> > > > > -
> > > > >
> > > > > I looked at the original scss vs yours and I'm wondering why you
> > don't
> > > > > have dispaly: inline-block, border=0 ect.
> > > > > -
> > > > >
> > > > > Why do you need the class rd - why can you add it to your default
> > > > > button class. Try it and figure out why you don't need it.
> > > > > -
> > > > >
> > > > > Why in the props are you setting a default background color
> object?
> > > > > -
> > > > >
> > > > > Why in button style do you have position: "relative",
> > > > > zIndex: 0,
> > > > > -
> > > > >
> > > > > This is really in a different task but there should not be a
> > different
> > > > > solution for if the background color is linear variant or a color.
> > > There
> > > > > should be an outline class and you should apply it.
> > > > > -
> > > > >
> > > > > This can all be simplified as the correct class can be read in
> > > > > directly from the prop passed in.
> > > > > let className =${style.button} ; className += extras.borderRadius
> ?
> > ""
> > > > > : ${style.rd} ; className += extras.fontSize ? "" : (size === "sm"
> > &&
> > > > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > > > -
> > > > >
> > > > > In general you should get rid of any inline styles unless you need
> > > > > them like in the case of background, you have no choice. so
> > position:
> > > > > "relative" - should not be there ect.
> > > > > -
> > > > >
> > > > > I'm running storybook and see the text is not coming up uppercase?
> > > > > -
> > > > >
> > > > > Simplify this line also onClick={onClickFunction && (() =>
> > > > > onClickFunction())}
> > > > >
> > > > > —
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > > >
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > >
> > > >
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > >
> > > >
> > > > > .
> > > > > You are receiving this because you authored the thread.Message ID:
> > > > > ***@***.***>
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
>
> >
> > >
> > > > .
> > > > You are receiving this because you commented.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562371237>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM3UTRK3AR4YBEX2EWL2HPFHNAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM3TCMRTG4>
>
> >
> > > .
> > > You are receiving this because you authored the thread.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562386492>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/A5BZJKHGDTEOQIALJLTKKAD2HPHL7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM4DMNBZGI>
>
> > .
> > You are receiving this because you commented.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562411573>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRMYV3XDJTHOSZ26CJJT2HPKM3AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGQYTCNJXGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-26 10:27 UTC, leowald commented
It should make no difference.

On Thu, Dec 26, 2024 at 12:26 PM SKupferstein ***@***.***>
wrote:

> ok
> and can we decide that in 'others' the user can't put in border radius...?
> because this is making it very complicated:)
>
> On Thu, 26 Dec 2024 at 12:24, leowald ***@***.***> wrote:
>
> > Yes
> >
> > On Thu, Dec 26, 2024 at 11:58 AM SKupferstein ***@***.***>
> > wrote:
> >
> > > Is it ok if I work from issue 83 on both issues?
> > >
> > > On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:
> > >
> > > > I actually took out number 7, it is fine and you can ignore.
> > > > All other things can be done and should be to bring your code up a
> > > level.
> > > > Again this is not an easy task - but it is all doable the way I'm
> > > saying.
> > > > (the only other thing you can probably ignore if you have a good
> > reason
> > > > for
> > > > it is why you don't put the display: inline-block.
> > > >
> > > > On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> > > > wrote:
> > > >
> > > > > Hi,
> > > > > 1. changed display to flex so that the icon should be in one line
> > with
> > > > > text, and border 0 - had that in the inline style - border:
> > > > > outline && typeof backgroundColor == "string"
> > > > > ? `1px solid ${getBackground(backgroundColor)}`
> > > > > : "none",
> > > > > 2. class rd - basically, if a bootstrap theme is applied, it
> > > overwrites
> > > > > the
> > > > > border radius, therefore I had to add the !important tag to it,
> but
> > if
> > > > the
> > > > > user adds his own border radius in "others", it won't override, so
> I
> > > put
> > > > > it
> > > > > in an extra class to add it conditionally.
> > > > > 3. Did it when you asked me to make css look like template and I
> > > wasn't
> > > > > sure what you meant... guess I can remove
> > > > > 4. These I added in the other tasks dealing with gradient border
> and
> > > > text,
> > > > > it's not necessary here but I guess they'll be merged in the end
> > > > anyway...
> > > > > 5. If the background color is gradient then I couldn't add it to
> the
> > > > > background, I had to add a div under the text with the gradient
> > > outline
> > > > > 6.Will do
> > > > > 7.In the template you used "capitalize" which only changes the
> first
> > > > > letter
> > > > > to uppercase - let me know if I should change
> > > > > 8.Will do
> > > > >
> > > > > Thank you
> > > > >
> > > > > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> > > > >
> > > > > > ***@***.**** requested changes on this pull request.
> > > > > >
> > > > > > You are making progress..
> > > > > > btw, this issue is meant to take a long time - it is
> complicated..
> > > > > >
> > > > > > -
> > > > > >
> > > > > > I looked at the original scss vs yours and I'm wondering why you
> > > don't
> > > > > > have dispaly: inline-block, border=0 ect.
> > > > > > -
> > > > > >
> > > > > > Why do you need the class rd - why can you add it to your
> default
> > > > > > button class. Try it and figure out why you don't need it.
> > > > > > -
> > > > > >
> > > > > > Why in the props are you setting a default background color
> > object?
> > > > > > -
> > > > > >
> > > > > > Why in button style do you have position: "relative",
> > > > > > zIndex: 0,
> > > > > > -
> > > > > >
> > > > > > This is really in a different task but there should not be a
> > > different
> > > > > > solution for if the background color is linear variant or a
> color.
> > > > There
> > > > > > should be an outline class and you should apply it.
> > > > > > -
> > > > > >
> > > > > > This can all be simplified as the correct class can be read in
> > > > > > directly from the prop passed in.
> > > > > > let className =${style.button} ; className +=
> extras.borderRadius
> > ?
> > > ""
> > > > > > : ${style.rd} ; className += extras.fontSize ? "" : (size ===
> "sm"
> > > &&
> > > > > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > > > > -
> > > > > >
> > > > > > In general you should get rid of any inline styles unless you
> need
> > > > > > them like in the case of background, you have no choice. so
> > > position:
> > > > > > "relative" - should not be there ect.
> > > > > > -
> > > > > >
> > > > > > I'm running storybook and see the text is not coming up
> uppercase?
> > > > > > -
> > > > > >
> > > > > > Simplify this line also onClick={onClickFunction && (() =>
> > > > > > onClickFunction())}
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > >
> > > >
> > > > >
> > > > > > or unsubscribe
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > >
> > > >
> > > > >
> > > > > > .
> > > > > > You are receiving this because you authored the thread.Message
> ID:
> > > > > > ***@***.***>
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
> > >
> > > >
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
>
> >
> > >
> > > >
> > > > > .
> > > > > You are receiving this because you commented.Message ID:
> > > > > ***@***.***>
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562371237>,
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM3UTRK3AR4YBEX2EWL2HPFHNAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM3TCMRTG4>
>
> >
> > >
> > > > .
> > > > You are receiving this because you authored the thread.Message ID:
> > > > ***@***.***>
> > > >
> > >
> > > —
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562386492>,
>
> >
> > > or unsubscribe
> > > <
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKHGDTEOQIALJLTKKAD2HPHL7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM4DMNBZGI>
>
> >
> > > .
> > > You are receiving this because you commented.Message ID:
> > > ***@***.***>
> > >
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562411573>,
>
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/BFNBRMYV3XDJTHOSZ26CJJT2HPKM3AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGQYTCNJXGM>
>
> > .
> > You are receiving this because you authored the thread.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562414135>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5BZJKEHPQJPMTXEKRHLEC32HPKVTAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGQYTIMJTGU>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-12-26 11:22 UTC, SKupferstein commented
OK, I fixed everything. Regarding bootstrap I'm facing an interesting issue:
Looks like the way bootstrap styles are applied in the regular application
is different to the way they are applied in storybook.
From my understanding, in storybook the scss style override the
bootstrap style elements, while in the application the bootstrap style
elements override the scss styles.
Currently, I have two issue
1. issue with bootstrap in the application but not in storybook:
bootstrap border-radius overrides the border radius I've set in my sccs.
Originally in order to avoid that I've added the !important tag, but then I
have a problem with people trying to override it with passing border-radius
into props, that is why I have put it in a separate class but you told me
to remove...)
2. issue with bootstrap in storybook but not in the application:
scss border:0 overrides bootstrap's 'outline' class style elements.
Originally in order to avoid that I set the border to 0 using inline style
but you told me to remove....

I was wondering how I should go about these two issues.
Thanks

On Thu, 26 Dec 2024 at 12:28, leowald ***@***.***> wrote:

> It should make no difference.
>
> On Thu, Dec 26, 2024 at 12:26 PM SKupferstein ***@***.***>
> wrote:
>
> > ok
> > and can we decide that in 'others' the user can't put in border
> radius...?
> > because this is making it very complicated:)
> >
> > On Thu, 26 Dec 2024 at 12:24, leowald ***@***.***> wrote:
> >
> > > Yes
> > >
> > > On Thu, Dec 26, 2024 at 11:58 AM SKupferstein ***@***.***>
> > > wrote:
> > >
> > > > Is it ok if I work from issue 83 on both issues?
> > > >
> > > > On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:
> > > >
> > > > > I actually took out number 7, it is fine and you can ignore.
> > > > > All other things can be done and should be to bring your code up a
> > > > level.
> > > > > Again this is not an easy task - but it is all doable the way I'm
> > > > saying.
> > > > > (the only other thing you can probably ignore if you have a good
> > > reason
> > > > > for
> > > > > it is why you don't put the display: inline-block.
> > > > >
> > > > > On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> > > > > wrote:
> > > > >
> > > > > > Hi,
> > > > > > 1. changed display to flex so that the icon should be in one
> line
> > > with
> > > > > > text, and border 0 - had that in the inline style - border:
> > > > > > outline && typeof backgroundColor == "string"
> > > > > > ? `1px solid ${getBackground(backgroundColor)}`
> > > > > > : "none",
> > > > > > 2. class rd - basically, if a bootstrap theme is applied, it
> > > > overwrites
> > > > > > the
> > > > > > border radius, therefore I had to add the !important tag to it,
> > but
> > > if
> > > > > the
> > > > > > user adds his own border radius in "others", it won't override,
> so
> > I
> > > > put
> > > > > > it
> > > > > > in an extra class to add it conditionally.
> > > > > > 3. Did it when you asked me to make css look like template and I
> > > > wasn't
> > > > > > sure what you meant... guess I can remove
> > > > > > 4. These I added in the other tasks dealing with gradient border
> > and
> > > > > text,
> > > > > > it's not necessary here but I guess they'll be merged in the end
> > > > > anyway...
> > > > > > 5. If the background color is gradient then I couldn't add it to
> > the
> > > > > > background, I had to add a div under the text with the gradient
> > > > outline
> > > > > > 6.Will do
> > > > > > 7.In the template you used "capitalize" which only changes the
> > first
> > > > > > letter
> > > > > > to uppercase - let me know if I should change
> > > > > > 8.Will do
> > > > > >
> > > > > > Thank you
> > > > > >
> > > > > > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> > > > > >
> > > > > > > ***@***.**** requested changes on this pull request.
> > > > > > >
> > > > > > > You are making progress..
> > > > > > > btw, this issue is meant to take a long time - it is
> > complicated..
> > > > > > >
> > > > > > > -
> > > > > > >
> > > > > > > I looked at the original scss vs yours and I'm wondering why
> you
> > > > don't
> > > > > > > have dispaly: inline-block, border=0 ect.
> > > > > > > -
> > > > > > >
> > > > > > > Why do you need the class rd - why can you add it to your
> > default
> > > > > > > button class. Try it and figure out why you don't need it.
> > > > > > > -
> > > > > > >
> > > > > > > Why in the props are you setting a default background color
> > > object?
> > > > > > > -
> > > > > > >
> > > > > > > Why in button style do you have position: "relative",
> > > > > > > zIndex: 0,
> > > > > > > -
> > > > > > >
> > > > > > > This is really in a different task but there should not be a
> > > > different
> > > > > > > solution for if the background color is linear variant or a
> > color.
> > > > > There
> > > > > > > should be an outline class and you should apply it.
> > > > > > > -
> > > > > > >
> > > > > > > This can all be simplified as the correct class can be read in
> > > > > > > directly from the prop passed in.
> > > > > > > let className =${style.button} ; className +=
> > extras.borderRadius
> > > ?
> > > > ""
> > > > > > > : ${style.rd} ; className += extras.fontSize ? "" : (size ===
> > "sm"
> > > > &&
> > > > > > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > > > > > -
> > > > > > >
> > > > > > > In general you should get rid of any inline styles unless you
> > need
> > > > > > > them like in the case of background, you have no choice. so
> > > > position:
> > > > > > > "relative" - should not be there ect.
> > > > > > > -
> > > > > > >
> > > > > > > I'm running storybook and see the text is not coming up
> > uppercase?
> > > > > > > -
> > > > > > >
> > > > > > > Simplify this line also onClick={onClickFunction && (() =>
> > > > > > > onClickFunction())}
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > > or unsubscribe
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > > .
> > > > > > > You are receiving this because you authored the thread.Message
> > ID:
> > > > > > > ***@***.***>
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> > > https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
>
> > > >
> > > > >
> > > > > > or unsubscribe
> > > > > > <
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
>
> >
> > >
> > > >
> > > > >
> > > > > > .
> > > > > > You are receiving this because you commented.Message ID:
> > > > > > ***@***.***>
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly, view it on GitHub
> > > > > <
> > https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562371237>,
> > >
> > > >
> > > > > or unsubscribe
> > > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM3UTRK3AR4YBEX2EWL2HPFHNAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGM3TCMRTG4>
>
> >
> > >
> > > >
> > > > > .
> > > > > You are receiving this because you authored the thread.Message ID:
> > > > > ***@***.***>
> > > > >
> > > >
> > > > —
> > > > Reply to this email directly, view it on GitHub
> > > > <
> https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562386492>,
> >
> > >
> > > > or unsubscribe
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKHGDTEOQIALJLTKKAD2HPHL7AVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWW [...]

2024-12-26 14:18 UTC, leowald commented
I'm not sure if this is what you mean but I actually did it a bit
differently and it may solve your problem.
I actually defined my own class with the same colors of bootstrap but
didn't use bootstrap css for it. That is fine to do also and may fix your
issue.
But not sure I fully understand your issue.

On Thu, Dec 26, 2024 at 1:23 PM SKupferstein ***@***.***>
wrote:

> OK, I fixed everything. Regarding bootstrap I'm facing an interesting
> issue:
> Looks like the way bootstrap styles are applied in the regular application
> is different to the way they are applied in storybook.
> From my understanding, in storybook the scss style override the
> bootstrap style elements, while in the application the bootstrap style
> elements override the scss styles.
> Currently, I have two issue
> 1. issue with bootstrap in the application but not in storybook:
> bootstrap border-radius overrides the border radius I've set in my sccs.
> Originally in order to avoid that I've added the !important tag, but then
> I
> have a problem with people trying to override it with passing
> border-radius
> into props, that is why I have put it in a separate class but you told me
> to remove...)
> 2. issue with bootstrap in storybook but not in the application:
> scss border:0 overrides bootstrap's 'outline' class style elements.
> Originally in order to avoid that I set the border to 0 using inline style
> but you told me to remove....
>
> I was wondering how I should go about these two issues.
> Thanks
>
> On Thu, 26 Dec 2024 at 12:28, leowald ***@***.***> wrote:
>
> > It should make no difference.
> >
> > On Thu, Dec 26, 2024 at 12:26 PM SKupferstein ***@***.***>
> > wrote:
> >
> > > ok
> > > and can we decide that in 'others' the user can't put in border
> > radius...?
> > > because this is making it very complicated:)
> > >
> > > On Thu, 26 Dec 2024 at 12:24, leowald ***@***.***> wrote:
> > >
> > > > Yes
> > > >
> > > > On Thu, Dec 26, 2024 at 11:58 AM SKupferstein ***@***.***>
> > > > wrote:
> > > >
> > > > > Is it ok if I work from issue 83 on both issues?
> > > > >
> > > > > On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:
> > > > >
> > > > > > I actually took out number 7, it is fine and you can ignore.
> > > > > > All other things can be done and should be to bring your code up
> a
> > > > > level.
> > > > > > Again this is not an easy task - but it is all doable the way
> I'm
> > > > > saying.
> > > > > > (the only other thing you can probably ignore if you have a good
> > > > reason
> > > > > > for
> > > > > > it is why you don't put the display: inline-block.
> > > > > >
> > > > > > On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> > > > > > wrote:
> > > > > >
> > > > > > > Hi,
> > > > > > > 1. changed display to flex so that the icon should be in one
> > line
> > > > with
> > > > > > > text, and border 0 - had that in the inline style - border:
> > > > > > > outline && typeof backgroundColor == "string"
> > > > > > > ? `1px solid ${getBackground(backgroundColor)}`
> > > > > > > : "none",
> > > > > > > 2. class rd - basically, if a bootstrap theme is applied, it
> > > > > overwrites
> > > > > > > the
> > > > > > > border radius, therefore I had to add the !important tag to
> it,
> > > but
> > > > if
> > > > > > the
> > > > > > > user adds his own border radius in "others", it won't
> override,
> > so
> > > I
> > > > > put
> > > > > > > it
> > > > > > > in an extra class to add it conditionally.
> > > > > > > 3. Did it when you asked me to make css look like template and
> I
> > > > > wasn't
> > > > > > > sure what you meant... guess I can remove
> > > > > > > 4. These I added in the other tasks dealing with gradient
> border
> > > and
> > > > > > text,
> > > > > > > it's not necessary here but I guess they'll be merged in the
> end
> > > > > > anyway...
> > > > > > > 5. If the background color is gradient then I couldn't add it
> to
> > > the
> > > > > > > background, I had to add a div under the text with the
> gradient
> > > > > outline
> > > > > > > 6.Will do
> > > > > > > 7.In the template you used "capitalize" which only changes the
> > > first
> > > > > > > letter
> > > > > > > to uppercase - let me know if I should change
> > > > > > > 8.Will do
> > > > > > >
> > > > > > > Thank you
> > > > > > >
> > > > > > > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> > > > > > >
> > > > > > > > ***@***.**** requested changes on this pull request.
> > > > > > > >
> > > > > > > > You are making progress..
> > > > > > > > btw, this issue is meant to take a long time - it is
> > > complicated..
> > > > > > > >
> > > > > > > > -
> > > > > > > >
> > > > > > > > I looked at the original scss vs yours and I'm wondering why
> > you
> > > > > don't
> > > > > > > > have dispaly: inline-block, border=0 ect.
> > > > > > > > -
> > > > > > > >
> > > > > > > > Why do you need the class rd - why can you add it to your
> > > default
> > > > > > > > button class. Try it and figure out why you don't need it.
> > > > > > > > -
> > > > > > > >
> > > > > > > > Why in the props are you setting a default background color
> > > > object?
> > > > > > > > -
> > > > > > > >
> > > > > > > > Why in button style do you have position: "relative",
> > > > > > > > zIndex: 0,
> > > > > > > > -
> > > > > > > >
> > > > > > > > This is really in a different task but there should not be a
> > > > > different
> > > > > > > > solution for if the background color is linear variant or a
> > > color.
> > > > > > There
> > > > > > > > should be an outline class and you should apply it.
> > > > > > > > -
> > > > > > > >
> > > > > > > > This can all be simplified as the correct class can be read
> in
> > > > > > > > directly from the prop passed in.
> > > > > > > > let className =${style.button} ; className +=
> > > extras.borderRadius
> > > > ?
> > > > > ""
> > > > > > > > : ${style.rd} ; className += extras.fontSize ? "" : (size
> ===
> > > "sm"
> > > > > &&
> > > > > > > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > > > > > > -
> > > > > > > >
> > > > > > > > In general you should get rid of any inline styles unless
> you
> > > need
> > > > > > > > them like in the case of background, you have no choice. so
> > > > > position:
> > > > > > > > "relative" - should not be there ect.
> > > > > > > > -
> > > > > > > >
> > > > > > > > I'm running storybook and see the text is not coming up
> > > uppercase?
> > > > > > > > -
> > > > > > > >
> > > > > > > > Simplify this line also onClick={onClickFunction && (() =>
> > > > > > > > onClickFunction())}
> > > > > > > >
> > > > > > > > —
> > > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > > <
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > >
> > > > > > > > or unsubscribe
> > > > > > > > <
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > >
> > > > > > > > .
> > > > > > > > You are receiving this because you authored the
> thread.Message
> > > ID:
> > > > > > > > ***@***.***>
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > <
> > > >
> https://github.com/leowald/yeshtikvah/pull/82#issuecomment-2562286296>,
> >
> > > > >
> > > > > >
> > > > > > > or unsubscribe
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/A5BZJKDWRNVDKXTCDSOHKPL2HOZ6BAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRSGI4DMMRZGY>
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > > .
> > > > > > > You are receiving this because you commented.Message ID:
> > > > > > > ***@***.***>
> > > > > > >
> > > > > >
> > > > > > —
> > >  [...]

2024-12-29 08:15 UTC, SKupferstein commented
That is smart and solves all my problems... I didn't even think in that
direction, for some reason I was under the impression that you 'davka'
wanted me to use bootstrap...
I just pushed again, hope all is right this time:)

On Thu, 26 Dec 2024 at 16:19, leowald ***@***.***> wrote:

> I'm not sure if this is what you mean but I actually did it a bit
> differently and it may solve your problem.
> I actually defined my own class with the same colors of bootstrap but
> didn't use bootstrap css for it. That is fine to do also and may fix your
> issue.
> But not sure I fully understand your issue.
>
> On Thu, Dec 26, 2024 at 1:23 PM SKupferstein ***@***.***>
> wrote:
>
> > OK, I fixed everything. Regarding bootstrap I'm facing an interesting
> > issue:
> > Looks like the way bootstrap styles are applied in the regular
> application
> > is different to the way they are applied in storybook.
> > From my understanding, in storybook the scss style override the
> > bootstrap style elements, while in the application the bootstrap style
> > elements override the scss styles.
> > Currently, I have two issue
> > 1. issue with bootstrap in the application but not in storybook:
> > bootstrap border-radius overrides the border radius I've set in my sccs.
> > Originally in order to avoid that I've added the !important tag, but
> then
> > I
> > have a problem with people trying to override it with passing
> > border-radius
> > into props, that is why I have put it in a separate class but you told
> me
> > to remove...)
> > 2. issue with bootstrap in storybook but not in the application:
> > scss border:0 overrides bootstrap's 'outline' class style elements.
> > Originally in order to avoid that I set the border to 0 using inline
> style
> > but you told me to remove....
> >
> > I was wondering how I should go about these two issues.
> > Thanks
> >
> > On Thu, 26 Dec 2024 at 12:28, leowald ***@***.***> wrote:
> >
> > > It should make no difference.
> > >
> > > On Thu, Dec 26, 2024 at 12:26 PM SKupferstein ***@***.***>
> > > wrote:
> > >
> > > > ok
> > > > and can we decide that in 'others' the user can't put in border
> > > radius...?
> > > > because this is making it very complicated:)
> > > >
> > > > On Thu, 26 Dec 2024 at 12:24, leowald ***@***.***> wrote:
> > > >
> > > > > Yes
> > > > >
> > > > > On Thu, Dec 26, 2024 at 11:58 AM SKupferstein ***@***.***>
> > > > > wrote:
> > > > >
> > > > > > Is it ok if I work from issue 83 on both issues?
> > > > > >
> > > > > > On Thu, 26 Dec 2024 at 11:40, leowald ***@***.***> wrote:
> > > > > >
> > > > > > > I actually took out number 7, it is fine and you can ignore.
> > > > > > > All other things can be done and should be to bring your code
> up
> > a
> > > > > > level.
> > > > > > > Again this is not an easy task - but it is all doable the way
> > I'm
> > > > > > saying.
> > > > > > > (the only other thing you can probably ignore if you have a
> good
> > > > > reason
> > > > > > > for
> > > > > > > it is why you don't put the display: inline-block.
> > > > > > >
> > > > > > > On Thu, Dec 26, 2024 at 10:03 AM SKupferstein ***@***.***>
> > > > > > > wrote:
> > > > > > >
> > > > > > > > Hi,
> > > > > > > > 1. changed display to flex so that the icon should be in one
> > > line
> > > > > with
> > > > > > > > text, and border 0 - had that in the inline style - border:
> > > > > > > > outline && typeof backgroundColor == "string"
> > > > > > > > ? `1px solid ${getBackground(backgroundColor)}`
> > > > > > > > : "none",
> > > > > > > > 2. class rd - basically, if a bootstrap theme is applied, it
> > > > > > overwrites
> > > > > > > > the
> > > > > > > > border radius, therefore I had to add the !important tag to
> > it,
> > > > but
> > > > > if
> > > > > > > the
> > > > > > > > user adds his own border radius in "others", it won't
> > override,
> > > so
> > > > I
> > > > > > put
> > > > > > > > it
> > > > > > > > in an extra class to add it conditionally.
> > > > > > > > 3. Did it when you asked me to make css look like template
> and
> > I
> > > > > > wasn't
> > > > > > > > sure what you meant... guess I can remove
> > > > > > > > 4. These I added in the other tasks dealing with gradient
> > border
> > > > and
> > > > > > > text,
> > > > > > > > it's not necessary here but I guess they'll be merged in the
> > end
> > > > > > > anyway...
> > > > > > > > 5. If the background color is gradient then I couldn't add
> it
> > to
> > > > the
> > > > > > > > background, I had to add a div under the text with the
> > gradient
> > > > > > outline
> > > > > > > > 6.Will do
> > > > > > > > 7.In the template you used "capitalize" which only changes
> the
> > > > first
> > > > > > > > letter
> > > > > > > > to uppercase - let me know if I should change
> > > > > > > > 8.Will do
> > > > > > > >
> > > > > > > > Thank you
> > > > > > > >
> > > > > > > > On Wed, 25 Dec 2024 at 13:21, leowald ***@***.***> wrote:
> > > > > > > >
> > > > > > > > > ***@***.**** requested changes on this pull request.
> > > > > > > > >
> > > > > > > > > You are making progress..
> > > > > > > > > btw, this issue is meant to take a long time - it is
> > > > complicated..
> > > > > > > > >
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > I looked at the original scss vs yours and I'm wondering
> why
> > > you
> > > > > > don't
> > > > > > > > > have dispaly: inline-block, border=0 ect.
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > Why do you need the class rd - why can you add it to your
> > > > default
> > > > > > > > > button class. Try it and figure out why you don't need it.
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > Why in the props are you setting a default background
> color
> > > > > object?
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > Why in button style do you have position: "relative",
> > > > > > > > > zIndex: 0,
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > This is really in a different task but there should not be
> a
> > > > > > different
> > > > > > > > > solution for if the background color is linear variant or
> a
> > > > color.
> > > > > > > There
> > > > > > > > > should be an outline class and you should apply it.
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > This can all be simplified as the correct class can be
> read
> > in
> > > > > > > > > directly from the prop passed in.
> > > > > > > > > let className =${style.button} ; className +=
> > > > extras.borderRadius
> > > > > ?
> > > > > > ""
> > > > > > > > > : ${style.rd} ; className += extras.fontSize ? "" : (size
> > ===
> > > > "sm"
> > > > > > &&
> > > > > > > > > style.sm) || (size === "lg" && style.lg) || style.md;
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > In general you should get rid of any inline styles unless
> > you
> > > > need
> > > > > > > > > them like in the case of background, you have no choice.
> so
> > > > > > position:
> > > > > > > > > "relative" - should not be there ect.
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > I'm running storybook and see the text is not coming up
> > > > uppercase?
> > > > > > > > > -
> > > > > > > > >
> > > > > > > > > Simplify this line also onClick={onClickFunction && (() =>
> > > > > > > > > onClickFunction())}
> > > > > > > > >
> > > > > > > > > —
> > > > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > > > <
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/leowald/yeshtikvah/pull/82#pullrequestreview-2522552496>,
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > >
> > > > > > > >
> > > > > > > > > or unsubscribe
> > > > > > > > > <
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe-auth/BFNBRM5RQ4YZ5WIMCATFCFD2HKIMXAVCNFSM6AAAAABTUO4WDGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRSGU2TENBZGY>
>
> >
> > >
> > > >
> > > > >
> > > > > >
> > > > > > >
> > > > > > > >
> > > > > > > > > .
> > > > > > > > > You are receiving t [...]

2025-01-01 10:02 UTC, closed without merging