initial commit for faker-menu api
leowald/yeshtikvah pull request #91
Opened 2024-12-24 10:20 UTC by CLobenstein

Hi Leora

I just wanted to know if you could check this...
I know I'm still going to have to change one part - that if 'title' is Home, then it has to take you to /App.... but I just wanted to know if what I have done so far is correct?

Thanks

2024-12-24 12:42 UTC, leowald requested changes
Overall it looks really good. 
The API call should be at menu though not menu / menuLinks.
Also the page_id should only be for pages that have the template Page.
Also the names of the menu items should not be fixed but should be random names. The templates have to be fixed. The url also does not have to be fixed. Also it needs to generate App.

2024-12-24 20:26 UTC, CLobenstein commented
Thanks!
The reason I did it that way is because on the list it says that Menu has
to be an object that holds an array... Not just an array....
What do you mean 'the template Page'?
Does it matter if it's fixed? Otherwise, can I generate a random url? But
does the end still have to be /accounts?

On Tue, Dec 24, 2024 at 2:42 PM leowald ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Overall it looks really good.
> The API call should be at menu though not menu / menuLinks.
> Also the page_id should only be for pages that have the template Page.
> Also the names of the menu items should not be fixed but should be random
> names. The templates have to be fixed. The url also does not have to be
> fixed. Also it needs to generate App.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/leowald/yeshtikvah/pull/91#pullrequestreview-2521923757>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFNBRMR7QWS2ZUJXEILQX6L2HFJE7AVCNFSM6AAAAABUEPYJJGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRRHEZDGNZVG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-25 09:44 UTC, CLobenstein commented
Hi Leora - please can you check the 'change to second commit' and not the one before. Thanks

2024-12-25 11:33 UTC, leowald requested changes
Hi,
Please add another page under pages called Page (change About to Page)
Only when the template is "page" do we include the page_id
Will the title ever be Home?
Otherwise looks great.

2024-12-26 09:51 UTC, leowald requested changes
Please test fully before you push again.
I see a few errors: for example it is generating a few times an object that looks like this:
[`{"id":"bbcf5855c0f9abd5d7379aca","title":"wafer","children":[],"url":"","template":"","page_id":""}`
 {"id":"30ac47e320c26b10f296f0fb","title":"pillbox","children":[],"url":"","template":"","page_id":""}](url)

Empty template and empty url but it does not have children.

Also I see one with a page_id even though the template is not page.

2024-12-28 21:13 UTC, leowald requested changes
I ran the code and see this - there is a page id here. Please test very very well before you push.

`{"id":"0ad9bb940dbbbde4826b0cfb","title":"citizen","children":
			
			[{"id":"d9a4c5693a7bb606d8cfbcde","title":"barracks","children":"","url":"/donate","template":"./pages/Donate","page_id":""},
				{"id":"e373c65aeed7f9a225f7e0d5","title":"cannon","children":"","url":"/stories","template":"./pages/Stories","page_id":""},
				{"id":"2df1f6b6b9c4dcfebeb57a4e","title":"kick","children":"","url":"/pesukim","template":"./pages/Pesukim","page_id":""}],"url":"","template":"","page_id":46},`

2025-01-01 10:00 UTC, leowald approved these changes
looks great

2025-01-01 10:02 UTC, merged